services:
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - '6379:6379'

  myapp:
    build: .
    container_name: myapp
    ports:
      - '5000:8000'
    volumes:
      - .:/app
    depends_on:
      - redis
